apiVersion: v1
kind: Service
metadata:
  name: mountebank-svc
  labels:
    app: mountebank-svc
spec:
  selector:
    app: mountebank-app
  type: LoadBalancer
  ports:
    - port: 2525
      name: mountebank
      targetPort: 2525
      nodePort: 30000
      protocol: TCP
    - port: 3000
      name: imposterdefault
      targetPort: 3000
      nodePort: 30001
      protocol: TCP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mountebank-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mountebank-app
spec:
  selector:
    matchLabels:
      app: mountebank-app
  template:
    metadata:
      labels:
        app: mountebank-app
    spec:
      containers:
      - name: mountebank-app
        image: deividbatfish2/mb:1.0.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 2525
          name: mountebank
        - containerPort: 3000
          name: imposterdefault
        volumeMounts:
          - mountPath: /data
            name: mbdb-volume
      volumes:
        - name: mbdb-volume
          persistentVolumeClaim: 
            claimName: mountebank-pvc